### ISSUE TITLE
when we click on the wishlist icon then the there must be some effect

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Deluxe-Hotel-LCC-Store-Redesign#10]
**Actual result:**
When we click on the wishlist icon, then no css effect is given.
![image](https://user-images.githubusercontent.com/102131636/167390306-d7ed9f80-2e54-41f9-8402-b29bceb60a35.png)

**Expected result:**
when we click on the wishlist icon then the there must be some effect.

**Comment by ui-nitinrai** [comment]
Hover effect added

**Comment by sudhanshu0603** [comment]
ok, resolved
