### ISSUE TITLE
The count is not increasing on the cart icon and wishlist in the header .

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Deluxe-Hotel-LCC-Store-Redesign#11]
**Actual result:**
The count is not increasing on the cart icon and wishlist in the header .
![image](https://user-images.githubusercontent.com/102131636/167390693-a9396366-c226-4da3-bda1-3d9dd38a2708.png)

**Expected result:**
The count have to increase when we click on the addtocart button on the header icon.

**Comment by devAbhishekYadav** [comment]
Sudhanshu that's the functionality of the theme where if you have items in your cart then the dot would be shown else no dot would be shown.

**Comment by devAbhishekYadav** [comment]
![image](https://user-images.githubusercontent.com/89765850/167541539-6e9d96f6-9b30-41c7-9b30-481472a65a49.png)
HS JOHN SON Store
