### ISSUE TITLE
The hover effect is not coming for the email on the footer.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Deluxe-Hotel-LCC-Store-Redesign#12]
**Actual result:**
The hover effect is not coming for the email on the footer.
![image](https://user-images.githubusercontent.com/102131636/167391172-58dc8bce-39cf-4c5f-894b-a3aaf7fb1a2a.png)
The video link: https://www.awesomescreenshot.com/video/8802728?key=1d44f044cc67934ddb3539a68da7b0ff

**Expected result:**
There must be the hover effect for the email as given for the mobile number.

**Comment by ui-nitinrai** [comment]
Video please

**Comment by ui-nitinrai** [comment]
Fixed [type error] ..Not an issue from designer side 
It happens while uploading content in the textarea of customize setting.

**Comment by sudhanshu0603** [comment]
ok, resolved
