### ISSUE TITLE
When we click on the social media icons then it is opening the shopify panel.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Deluxe-Hotel-LCC-Store-Redesign#15]
**Actual result:**
When we click on the social media icons then it is opening the shopify panel.
![image](https://user-images.githubusercontent.com/102131636/167397127-3a6bb839-2343-4d82-b27b-0a30249a230e.png)
![image](https://user-images.githubusercontent.com/102131636/167397150-ca436d49-20ac-4c9f-a856-597a101bb3e6.png)

**Expected result:**
The linking have to be given for the social media icons.

**Comment by devAbhishekYadav** [comment]
no social media links have been provided by client

**Comment by sudhanshu0603** [comment]
ok ,@abhishek
