### ISSUE TITLE
The color swatches are coming of white color.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Deluxe-Hotel-LCC-Store-Redesign#18]
**The url:**
https://deluxehotelco.com/collections/pillows/products/velvet-cushion-cover-pillowcase-solid-color-pillow-case-decor-sofa-throw-pillows-room-pillow-cover-decorative-wholesale-60x60?variant=42720403915006
**Actual result:**
The color swatches are coming of white color.
![image](https://user-images.githubusercontent.com/102131636/167401011-f37f7025-8714-49a2-9348-33e6890050ce.png)

**Expected result:**
We can use some color or the images for the swatches.( Suggestion.)

**Comment by devAbhishekYadav** [comment]
The color swatches are coming in white color because the color name are not real color names 
second these products are dummy products that have been imported from oberlo So these have a lot of variants and its not possible for me to upload/set swatches for each one of them.

**Comment by sudhanshu0603** [comment]
ok, fine
